void Exception_NonMaskableInt() { while (1); }
void Exception_HardFault() { while (1); }
void Exception_MemoryManagement() { while (1); }
void Exception_BusFault() { while (1); }
void Exception_UsageFault() { while (1); }
void Exception_SVCall() { while (1); }
void Exception_DebugMonitor() { while (1); }
void Exception_PendSV() { while (1); }
void Exception_SysTick() { while (1); }
void UnhandledException() { while (1); }
